In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:

dataset = pd.read_csv(r"C:\Users\SHAMSHER\Desktop\Training\AIML\StudentPerformanceFactors.csv")
dataset.head(3)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74

In [3]:
dataset.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

Fill Those Missing Values

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [5]:
dataset.select_dtypes(include='int64').columns

Index(['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores',
       'Tutoring_Sessions', 'Physical_Activity', 'Exam_Score'],
      dtype='object')

In [6]:
from sklearn.impute import SimpleImputer

In [7]:
si = SimpleImputer(strategy="mean")
ar = si.fit_transform(dataset[['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores',
       'Tutoring_Sessions', 'Physical_Activity', 'Exam_Score']])

In [8]:
new_dataSet = pd.DataFrame(ar,columns=dataset.select_dtypes(include='int64').columns)

In [9]:
new_dataSet.isnull().sum()

Hours_Studied        0
Attendance           0
Sleep_Hours          0
Previous_Scores      0
Tutoring_Sessions    0
Physical_Activity    0
Exam_Score           0
dtype: int64

Encoding

In [10]:
data = pd.read_csv(r"C:\Users\SHAMSHER\Downloads\student_performance_dataset.csv")
data.head(3)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A

In [ ]:
data.isnull().sum()

student_id                      0
gender                          0
study_time_hours                0
attendance_percent              0
sleep_hours                     0
parental_education            102
internet_access                 0
extracurricular_activities      0
part_time_job                   0
previous_grade                  0
final_exam_score                0
final_grade                     0
dtype: int64

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  1000 non-null   int64
 1   gender                      1000 non-null   object
 2   study_time_hours            1000 non-null   float64
 3   attendance_percent          1000 non-null   float64
 4   sleep_hours                 1000 non-null   float64
 5   parental_education          898 non-null    object
 6   internet_access             1000 non-null   object
 7   extracurricular_activities  1000 non-null   object
 8   part_time_job               1000 non-null   object
 9   previous_grade              1000 non-null   float64
 10  final_exam_score            1000 non-null   float64
 11  final_grade                 1000 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 93.9+ KB

In [13]:
data['parental_education'].fillna(data['parental_education'].mode()[0],inplace=True)  # filling missing vals

C:\Users\SHAMSHER\AppData\Local\Temp\ipykernel_31308\256430734.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['parental_education'].fillna(data['parental_education'].mode()[0],inplace=True)  # filling missing vals

In [14]:
# Encoding
en_data = data[['gender','internet_access']]
en_data

     gender internet_access
0      Male             Yes
1    Female             Yes
2      Male             Yes
3      Male             Yes
4      Male             Yes
..      ...             ...
995    Male             Yes
996    Male              No
997  Female             Yes
998  Female              No
999    Male             Yes

[1000 rows x 2 columns]

In [15]:
pd.get_dummies(en_data)

     gender_Female  gender_Male  internet_access_No  internet_access_Yes
0            False         True               False                 True
1             True        False               False                 True
2            False         True               False                 True
3            False         True               False                 True
4            False         True               False                 True
..             ...          ...                 ...                  ...
995          False         True               False                 True
996          False         True                True                False
997           True        False               False                 True
998           True        False                True                False
999          False         True               False                 True

[1000 rows x 4 columns]

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
ohe = OneHotEncoder(drop='first')

In [18]:
arr = ohe.fit_transform(en_data).toarray()

In [19]:
pd.DataFrame(arr,columns=["gender_Male","internet_access_Yes"])

     gender_Male  internet_access_Yes
0            1.0                  1.0
1            0.0                  1.0
2            1.0                  1.0
3            1.0                  1.0
4            1.0                  1.0
..           ...                  ...
995          1.0                  1.0
996          1.0                  0.0
997          0.0                  1.0
998          0.0                  0.0
999          1.0                  1.0

[1000 rows x 2 columns]

Label Encoding

In [ ]:
df = pd.dataframe