# Encoding

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\SHAMSHER\Downloads\student_performance_dataset.csv")
data.head(3)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A

In [5]:
data.isnull().sum()

student_id                      0
gender                          0
study_time_hours                0
attendance_percent              0
sleep_hours                     0
parental_education            102
internet_access                 0
extracurricular_activities      0
part_time_job                   0
previous_grade                  0
final_exam_score                0
final_grade                     0
dtype: int64

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  1000 non-null   int64
 1   gender                      1000 non-null   object
 2   study_time_hours            1000 non-null   float64
 3   attendance_percent          1000 non-null   float64
 4   sleep_hours                 1000 non-null   float64
 5   parental_education          898 non-null    object
 6   internet_access             1000 non-null   object
 7   extracurricular_activities  1000 non-null   object
 8   part_time_job               1000 non-null   object
 9   previous_grade              1000 non-null   float64
 10  final_exam_score            1000 non-null   float64
 11  final_grade                 1000 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 93.9+ KB

In [8]:
data['parental_education'].fillna(data['parental_education'].mode()[0],inplace=True)  # filling missing vals

C:\Users\SHAMSHER\AppData\Local\Temp\ipykernel_15260\256430734.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['parental_education'].fillna(data['parental_education'].mode()[0],inplace=True)  # filling missing vals

In [ ]:
# Encoding
en_data = data[['gender','internet_access']]
en_data

     gender internet_access
0      Male             Yes
1    Female             Yes
2      Male             Yes
3      Male             Yes
4      Male             Yes
..      ...             ...
995    Male             Yes
996    Male              No
997  Female             Yes
998  Female              No
999    Male             Yes

[1000 rows x 2 columns]

By using pandas and Sklearn

In [10]:
pd.get_dummies(en_data)

     gender_Female  gender_Male  internet_access_No  internet_access_Yes
0            False         True               False                 True
1             True        False               False                 True
2            False         True               False                 True
3            False         True               False                 True
4            False         True               False                 True
..             ...          ...                 ...                  ...
995          False         True               False                 True
996          False         True                True                False
997           True        False               False                 True
998           True        False                True                False
999          False         True               False                 True

[1000 rows x 4 columns]

# OneHotEncoder

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
ohe = OneHotEncoder(drop='first')

In [19]:
arr = ohe.fit_transform(en_data).toarray()
# arr

In [ ]:
pd.DataFrame(arr,columns=["gender_Male","internet_access_Yes"])

     gender_Male  internet_access_Yes
0            1.0                  1.0
1            0.0                  1.0
2            1.0                  1.0
3            1.0                  1.0
4            1.0                  1.0
..           ...                  ...
995          1.0                  1.0
996          1.0                  0.0
997          0.0                  1.0
998          0.0                  0.0
999          1.0                  1.0

[1000 rows x 2 columns]

# Label Encoding

In [17]:
df = pd.DataFrame({"name" : ["Sharry" , "Gill" , "Shamsher" , "SGILL" , "SharryGill"]})
df

         name
0      Sharry
1        Gill
2    Shamsher
3       SGILL
4  SharryGill

In [20]:
from sklearn.preprocessing import LabelEncoder

In [25]:
lb = LabelEncoder()
df["en_name"] = lb.fit_transform(df["name"])

In [26]:
df

         name  en_name
0      Sharry        3
1        Gill        0
2    Shamsher        2
3       SGILL        1
4  SharryGill        4

In [28]:
data.head(3)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A

In [34]:
d = data["parental_education"]

In [37]:
d.unique()

array(['Bachelors', 'High School', 'Masters', 'PhD'], dtype=object)

In [35]:
lb.fit(d)

LabelEncoder()

In [36]:
lb.transform(d)

array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 2, 0, 2, 1, 0, 0, 2, 2, 1, 1,
       1, 3, 1, 1, 2, 1, 0, 0, 0, 1, 2, 0, 2, 1, 1, 1, 1, 2, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 2, 2, 0, 0, 2, 0, 2, 0, 2, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 2, 0, 1, 2, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 2,
       1, 0, 1, 1, 0, 0, 3, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 2, 1, 1, 0, 0, 1, 1, 2, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 2, 1, 0, 1, 1, 1, 2, 2, 0, 0, 1, 1, 1, 1, 2, 1, 1, 3, 2, 1, 0,
       0, 1, 1, 2, 1, 2, 0, 0, 2, 2, 3, 1, 2, 1, 0, 0, 0, 0, 1, 1, 2, 0,
       1, 1, 1, 3, 1, 1, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0,
       2, 0, 1, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 3, 1, 1, 3, 0, 3, 0, 2, 0, 2, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 1, 1, 3,
       0, 0, 2, 2, 1, 1, 2, 1, 3, 1, 1, 3, 1, 1, 1, 3, 0, 2, 1, 2, 2, 1,
       0, 1, 1, 0, 1, 1, 2, 2, 2, 1, 0, 1, 2, 2, 0, 1, 0, 1, 0, 0, 2, 1,
       0, 1, 1, 2, 1, 0, 2, 3, 2, 1, 1, 0, 1, 1, 0, 1, 1, 1, 2, 3, 1, 3,
       3, 2, 1, 2, 1, 2, 1, 0, 0, 0, 1, 1, 2, 3, 1, 1, 1, 2, 2, 2, 1, 1,
       3, 1, 2, 2, 2, 1, 3, 1, 1, 2, 0, 2, 0, 1, 2, 0, 1, 2, 0, 0, 0, 2,
       2, 2, 1, 2, 2, 2, 0, 3, 2, 1, 0, 3, 1, 1, 2, 0, 1, 1, 1, 1, 2, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 3, 0, 0, 1, 1, 1, 1, 2, 0, 0, 0, 2, 1,
       2, 0, 0, 0, 1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 1,
       1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 0,
       2, 0, 3, 3, 1, 2, 0, 1, 0, 1, 2, 1, 0, 1, 3, 1, 2, 1, 1, 0, 1, 2,
       1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 3, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 3, 1, 3, 1, 0, 2, 1, 1, 2,
       3, 1, 1, 1, 0, 0, 0, 1, 2, 1, 1, 0, 2, 2, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 2, 1, 1, 0, 2, 1, 0, 1, 1, 1, 1, 3, 0, 2,
       1, 1, 1, 0, 0, 1, 0, 2, 0, 1, 1, 1, 1, 0, 0, 2, 0, 2, 1, 0, 2, 1,
       1, 3, 1, 2, 1, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 2, 0, 3, 0, 0, 1, 1, 1, 1, 0, 2, 1, 1, 2, 0, 3, 1, 1, 0, 1,
       2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 2, 2, 1, 0, 2, 0, 2, 1, 0, 2, 2, 2,
       0, 1, 0, 2, 0, 2, 0, 0, 1, 2, 0, 1, 1, 2, 0, 1, 1, 2, 1, 0, 0, 3,
       0, 2, 1, 0, 1, 1, 1, 1, 1, 1, 2, 2, 0, 1, 2, 0, 2, 2, 1, 0, 1, 0,
       1, 3, 1, 1, 2, 0, 0, 0, 3, 1, 3, 1, 2, 2, 1, 0, 1, 2, 0, 0, 1, 1,
       1, 1, 0, 3, 2, 0, 1, 2, 1, 0, 1, 1, 2, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       2, 1, 2, 0, 1, 2, 0, 0, 0, 0, 1, 0, 1, 2, 1, 1, 0, 2, 0, 1, 0, 1,
       1, 1, 0, 1, 2, 1, 0, 1, 1, 1, 0, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       2, 1, 1, 0, 2, 1, 0, 1, 1, 1, 2, 1, 1, 0, 2, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 2, 1, 1, 3, 0, 2, 1, 0, 0, 0, 2, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 3, 0, 0, 1, 1, 1, 0, 0, 1, 2, 1, 0, 1, 0, 2, 0, 3, 0, 3,
       0, 1, 1, 1, 1, 2, 2, 1, 1, 2, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 2,
       0, 0, 1, 1, 0, 2, 3, 1, 0, 1, 0, 2, 1, 1, 2, 1, 2, 0, 1, 1, 1, 2,
       2, 1, 1, 2, 2, 1, 0, 1, 1, 1, 0, 2, 1, 0, 2, 0, 3, 1, 1, 1, 1, 2,
       0, 0, 0, 2, 1, 1, 1, 0, 1, 0, 0, 1, 0, 3, 1, 0, 2, 0, 2, 0, 0, 1,
       2, 2, 1, 0, 1, 0, 0, 1, 2, 0, 2, 3, 0, 0, 0, 1, 2, 1, 3, 0, 1, 0,
       0, 3, 1, 2, 0, 1, 1, 0, 1, 0, 3, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 3, 0, 2, 1, 1, 1, 2])

# Ordinal Encoding

1. SkLearn    2. Map Fuction -> Techniques

1. Sklearn

In [48]:
odf = pd.DataFrame({"Size" : ["s","m","l","xl","s","m","l","xl","s","m","l","xl"]})
odf.head(4)

  Size
0    s
1    m
2    l
3   xl

In [42]:
ord_data = [["s","m","l","xl"]]

In [43]:
from sklearn.preprocessing import OrdinalEncoder

In [50]:
oe = OrdinalEncoder(categories=ord_data)
oe.fit(odf[["Size"]])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [53]:
odf["en_Size"] = oe.transform(df[["Size"]])
odf

   Size  en_Size
0     s      0.0
1     m      1.0
2     l      2.0
3    xl      3.0
4     s      0.0
5     m      1.0
6     l      2.0
7    xl      3.0
8     s      0.0
9     m      1.0
10    l      2.0
11   xl      3.0

# Map Function

In [55]:
ord_data1 = {"s" : 0 , "m" : 1,"l" : 2 , "xl" : 3}

In [60]:
odf["Size_en_map"] = odf["Size"].map(ord_data1)
odf

   Size  en_Size  Size_en  Size_en_map
0     s      0.0        0            0
1     m      1.0        1            1
2     l      2.0        2            2
3    xl      3.0        3            3
4     s      0.0        0            0
5     m      1.0        1            1
6     l      2.0        2            2
7    xl      3.0        3            3
8     s      0.0        0            0
9     m      1.0        1            1
10    l      2.0        2            2
11   xl      3.0        3            3

In [69]:
# Large data
data.head(3)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,0.0,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,1.0,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,0.0,Yes,No,Yes,88.5,97.3,A

In [63]:
data["parental_education"].unique()

array(['Bachelors', 'High School', 'Masters', 'PhD'], dtype=object)

In [64]:
en_data_ord = [['Bachelors', 'High School', 'Masters', 'PhD']]

In [65]:
oen = OrdinalEncoder(categories=en_data_ord)

In [68]:
data["parental_education"] = oen.fit_transform(data[["parental_education"]])